# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Server
DESTDIR = ./Win32/Debug
QT += core opengl gui
CONFIG += debug console
DEFINES += WIN64 QT_DLL
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(Server.pri)
QT += network